### PR TITLE
Worked on Darkmode button

### PR DESCRIPTION
**Pull request by ashfaque-mustaque**
did some work on dark mode toggle button hope you will merge my pr

### CODE REVIEW

**Comment by ishant9805** [comment]
I will merge your PR after reviewing the code. No need to worry!

**Comment by ashfaque-mustaque** [comment]
@ishant9805 brother still you did not merge my pr
Capturehack

**Comment by ishant9805** [comment]
Ah, you meant that. I actually don't get time to review your PR. As the PR is conflicting with the previous version, I need to review it before merging. Don't worry about the PR. It will be accepted before enough time. And your contribution won't go in a waste. Till then you can contribute to other projects on GitHub.

Lots of thanks to you for your contribution @ashfaque-mustaque

**Comment by ishant9805** [comment]
Check your @ashfaque-mustaque  hacktoberfest profile is it accepted, if you are confused about it ping me or send a screenshot.

**Comment by ashfaque-mustaque** [comment]
Yes brother Thanks for the merge.

**Pull request merged**
